import { useEffect, useMemo, useState } from "react";

import { clearAlert, clearAllAlerts, fetchAlerts } from "../api/queries";
import type { AlertsListResponse, RuntimeAlert } from "../types/alerts";

function formatTimestamp(value: string): string {
  try {
    return new Date(value).toLocaleString();
  } catch {
    return value;
  }
}

function severityLabel(severity: string): string {
  if (severity === "critical") return "Critical";
  if (severity === "warning") return "Warning";
  return "Info";
}

function severityStyle(severity: string): React.CSSProperties {
  if (severity === "critical") {
    return {
      background: "#fff1f2",
      border: "1px solid #fecdd3",
      color: "#9f1239",
    };
  }

  if (severity === "warning") {
    return {
      background: "#fffbeb",
      border: "1px solid #fde68a",
      color: "#92400e",
    };
  }

  return {
    background: "#eff6ff",
    border: "1px solid #bfdbfe",
    color: "#1d4ed8",
  };
}

export default function AlertsPage() {
  const [data, setData] = useState<AlertsListResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [busyKey, setBusyKey] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const alerts = useMemo<RuntimeAlert[]>(() => data?.items ?? [], [data]);

  async function loadAlerts() {
    setLoading(true);
    setError(null);

    try {
      const response = await fetchAlerts();
      setData(response);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load alerts");
    } finally {
      setLoading(false);
    }
  }

  async function handleClearAlert(alertKey: string) {
    setBusyKey(alertKey);

    try {
      await clearAlert(alertKey);
      await loadAlerts();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to clear alert");
    } finally {
      setBusyKey(null);
    }
  }

  async function handleClearAll() {
    setBusyKey("__all__");

    try {
      await clearAllAlerts();
      await loadAlerts();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to clear alerts");
    } finally {
      setBusyKey(null);
    }
  }

  useEffect(() => {
    void loadAlerts();

    const timer = window.setInterval(() => {
      void loadAlerts();
    }, 5000);

    return () => window.clearInterval(timer);
  }, []);

  return (
    <div style={{ display: "grid", gap: 16 }}>
      <section
        style={{
          background: "#ffffff",
          border: "1px solid #e5e7eb",
          borderRadius: 16,
          padding: 20,
          boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
        }}
      >
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            gap: 12,
            flexWrap: "wrap",
          }}
        >
          <div>
            <h1 style={{ margin: 0, fontSize: 28 }}>Alerts</h1>
            <p style={{ margin: "8px 0 0 0", color: "#4b5563" }}>
              Monitor active safety, watchdog, and operational alerts generated by BattleReef.
            </p>
          </div>

          <button
            onClick={() => void handleClearAll()}
            disabled={busyKey === "__all__" || alerts.length === 0}
            style={{
              border: "1px solid #d1d5db",
              borderRadius: 10,
              padding: "10px 14px",
              background: "#111827",
              color: "#ffffff",
              cursor: "pointer",
            }}
          >
            Clear All Alerts
          </button>
        </div>
      </section>

      {error ? (
        <section
          style={{
            background: "#fff1f2",
            border: "1px solid #fecdd3",
            borderRadius: 16,
            padding: 16,
            color: "#9f1239",
          }}
        >
          {error}
        </section>
      ) : null}

      <section
        style={{
          background: "#ffffff",
          border: "1px solid #e5e7eb",
          borderRadius: 16,
          padding: 20,
          boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
        }}
      >
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: 16,
            flexWrap: "wrap",
            gap: 12,
          }}
        >
          <div style={{ fontWeight: 700 }}>Active Alerts</div>
          <div style={{ color: "#6b7280" }}>
            {loading ? "Loading..." : `${alerts.length} active`}
          </div>
        </div>

        {alerts.length === 0 && !loading ? (
          <div
            style={{
              border: "1px dashed #d1d5db",
              borderRadius: 12,
              padding: 20,
              color: "#4b5563",
              background: "#f9fafb",
            }}
          >
            No active alerts. The watchdog layer currently reports normal operating conditions.
          </div>
        ) : null}

        <div style={{ display: "grid", gap: 12 }}>
          {alerts.map((alert) => (
            <article
              key={alert.key}
              style={{
                border: "1px solid #e5e7eb",
                borderRadius: 14,
                padding: 16,
                background: "#ffffff",
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  gap: 12,
                  alignItems: "flex-start",
                  flexWrap: "wrap",
                }}
              >
                <div style={{ display: "grid", gap: 8, flex: 1 }}>
                  <div style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" }}>
                    <span
                      style={{
                        ...severityStyle(alert.severity),
                        borderRadius: 999,
                        padding: "4px 10px",
                        fontSize: 12,
                        fontWeight: 700,
                      }}
                    >
                      {severityLabel(alert.severity)}
                    </span>
                    <span style={{ fontWeight: 700 }}>{alert.title}</span>
                  </div>

                  <div style={{ color: "#374151" }}>{alert.message}</div>

                  <div style={{ display: "grid", gap: 4, color: "#6b7280", fontSize: 13 }}>
                    <div>Key: {alert.key}</div>
                    <div>Source: {alert.source}</div>
                    <div>Created: {formatTimestamp(alert.created_at)}</div>
                    <div>Updated: {formatTimestamp(alert.updated_at)}</div>
                  </div>

                  {alert.metadata && Object.keys(alert.metadata).length > 0 ? (
                    <pre
                      style={{
                        margin: 0,
                        padding: 12,
                        borderRadius: 10,
                        background: "#f3f4f6",
                        color: "#111827",
                        overflowX: "auto",
                        fontSize: 12,
                      }}
                    >
                      {JSON.stringify(alert.metadata, null, 2)}
                    </pre>
                  ) : null}
                </div>

                <button
                  onClick={() => void handleClearAlert(alert.key)}
                  disabled={busyKey === alert.key}
                  style={{
                    border: "1px solid #d1d5db",
                    borderRadius: 10,
                    padding: "10px 14px",
                    background: "#ffffff",
                    color: "#111827",
                    cursor: "pointer",
                    minWidth: 110,
                  }}
                >
                  {busyKey === alert.key ? "Clearing..." : "Clear"}
                </button>
              </div>
            </article>
          ))}
        </div>
      </section>
    </div>
  );
}